export const CHANGE_INPUT_FIELD = 'CHANGE_INPUT_FIELD'
export const REQUEST_PENDING = 'REQUEST_PENDING';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';

export const REQUEST_CREATE_TODO_PENDING = 'REQUEST_CREATE_TODO_PENDING';
export const REQUEST_CREATE_TODO_FAILED = 'REQUEST_CREATE_TODO_FAILED';
export const REQUEST_CREATE_TODO_SUCCESS = 'REQUEST_CREATE_TODO_SUCCESS';
