export const CHANGE_INPUT_FIELD = 'CHANGE_INPUT_FIELD'
export const REQUEST_PENDING = 'REQUEST_PENDING';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';